const ProductList = [
  {
    "product": "hl50c",
    "product-image": "50c.jpg",
    "category-id": "1",
    "description": "HL50C - 2\" portable diesel clean water pump, powered by reliable air cooled diesel engines, is suitable for various applications like dewatering, agricultural, pool water removal, irrigation, etc. Strong-built pump housing and cast iron impeller extends the life of the pump. Carbon-ceramic mechanical seal designed for long and superior abrasion resistance. Self-priming design (Require initial priming to operate).",
    "specs": [
      {"Pump Type": "Centrifugal Pump"},
      {"Fuel Tank": "2.5 L"},
      {"Diameter": "2\" (50mm)"},
      {"Total Head": "31 m"},
      {"Suction Head": "8 m"},
      {"Discharge Volume": "600 L/min"},
      {"Pump Body": "Aluminum Alloy"},
      {"Impeller": "Cast Iron"},
      {"Mechanical Seal": "Carbon-Ceramic"},
      {"Engine Model": "HL170FA"},
      {"Engine Type": "Air Cooled Diesel Engine"},
      {"Start System": "Manual Start"},
      {"Displacement": "219 cc"},
      {"Fuel Consumption": "2.8kW (3.8hp) @3600rpm"},
      {"Rated Output": "347ml/kW.h @3600rpm"},
      {"Dry Weight": "40 kg"},
      {"Dimension": "560x440x510 mm"}
    ],
  },
  {
    "product": "hl80c",
    "product-image": "80c.jpg",
    "category-id": "1",
    "description": "HL50C - 2\" portable diesel clean water pump, powered by reliable air cooled diesel engines, is suitable for various applications like dewatering, agricultural, pool water removal, irrigation, etc. Strong-built pump housing and cast iron impeller extends the life of the pump. Carbon-ceramic mechanical seal designed for long and superior abrasion resistance. Self-priming design (Require initial priming to operate).",
    "specs": [
      {"Pump Type": "Centrifugal Pump"},
      {"Fuel Tank": "2.5 L"},
      {"Diameter": "2\" (50mm)"},
      {"Total Head": "31 m"},
      {"Suction Head": "8 m"},
      {"Discharge Volume": "600 L/min"},
      {"Pump Body": "Aluminum Alloy"},
      {"Impeller": "Cast Iron"},
      {"Mechanical Seal": "Carbon-Ceramic"},
      {"Engine Model": "HL170FA"},
      {"Engine Type": "Air Cooled Diesel Engine"},
      {"Start System": "Manual Start"},
      {"Displacement": "219 cc"},
      {"Fuel Consumption": "2.8kW (3.8hp) @3600rpm"},
      {"Rated Output": "347ml/kW.h @3600rpm"},
      {"Dry Weight": "40 kg"},
      {"Dimension": "560x440x510 mm"}
    ],
  },
  {
    "product": "hl100c",
    "product-image": "100c.jpg",
    "category-id": "1",
    "description": "HL100C - 4\" portable diesel clean water pump, powered by reliable air cooled diesel engines, is suitable for various applications like dewatering, agricultural, pool water removal, irrigation, etc. Strong-built pump housing and cast iron impeller extends the life of the pump. Carbon-ceramic mechanical seal designed for long and superior abrasion resistance. Self-priming design (Require initial priming to operate).",
    "specs": [
      {"Pump Type": "Centrifugal Pump"},
      {"Fuel Tank": "2.5 L"},
      {"Diameter": "2\" (50mm)"},
      {"Total Head": "31 m"},
      {"Suction Head": "8 m"},
      {"Discharge Volume": "600 L/min"},
      {"Pump Body": "Aluminum Alloy"},
      {"Impeller": "Cast Iron"},
      {"Mechanical Seal": "Carbon-Ceramic"},
      {"Engine Model": "HL170FA"},
      {"Engine Type": "Air Cooled Diesel Engine"},
      {"Start System": "Manual Start"},
      {"Displacement": "219 cc"},
      {"Fuel Consumption": "2.8kW (3.8hp) @3600rpm"},
      {"Rated Output": "347ml/kW.h @3600rpm"},
      {"Dry Weight": "40 kg"},
      {"Dimension": "560x440x510 mm"}
    ],
  },
  {
    "product": "BTE-3ZQ-16DQ",
    "product-image": "betelte-wood-chipper-web.jpg",
    "product-gallery": ["brush-chipper-BTE-3ZQ-16DQ-1.jpg", "brush-chipper-BTE-3ZQ-16DQ-2.jpg", "brush-chipper-BTE-3ZQ-16DQ-3.jpg"],
    "category-id": "2",
    "description": "Powered by 22kW, 380V electric motor, Betelte brush chipper BTE-3ZQ-16DQ is engineered with rich features, including intelligent hydraulic system, safer and more convenient knives, smart feeding, adjustable cutting speed. It also comes with a stationary model BTE-3ZQ-16DG.",
    "features": [
      "BTE-3ZQ-16DQ can be produced with stationary or portable configuration, to meet various applications.",
      "Reliable power source, 22KW electric motor by default. But, 35HP double-cylinder gasoline engine, or 31HP three-cylinder diesel engine is available upon request.",
      "Smart hydraulic system to make your job much easier and safer.",
      "Upgraded knife.",
      "Smart feeding system.",
      "Adjustable feeding speed."
    ],
    "specs": [
      {"Feed Roller Orientation": "Horizontal"},
      {"Feed Roller Clamp Load": "132 kg"},
      {"Feed Roller Minimum Distance to Drum": "5 mm"},
      {"Feed Roller Dimension": "φ300mm×285mm"},
      {"Feed Speed": "0∽0.4 m/s (adjustable)"},
      {"Feed Emergency Stop Switch": "Emergency Stop Switch (Left and Right)"},
      {"Emergency Stop Reset Method": "Turn and Loosen Emergency Switch"},
      {"Feed Control Bar": "Standard"},
      {"Positions": "Forward, Stop, Reverse"},
      {"Tank Capacity": "22 L"},
      {"Recommended Oil Type": "No. 46 Anti-wear Hydraulic Oil"},
      {"Pump Flow at Maximum RPM": "9.2 L/min"},
      {"Flow Control": "Yes"},
      {"Direction Control": "Yes"},
    ],
  },
];

export default ProductList;
